query getFolders {
  folderTree {
    ...GenericFolder
    entries {
      id
      entity {
        ... on Spark {
          ...GenericSpark
        }
        ... on Folder {
          ...GenericFolder
          entries {
             id
             entity {
               ... on Spark {
                 ...GenericSpark
               }
               ... on Folder {
                 ...GenericFolder
                 entries {
                    id
                 }
               }
             }
          }
        }
      }
    }
  }
}