query getFolders {
  folderTree {
    id
    name
    entries {
      id
      entity {
        ... on Spark {
          ...GenericSpark
        }
        ... on Folder {
          id
          name
          entries {
             id
             entity {
               ... on Spark {
                 ...GenericSpark
               }
               ... on Folder {
                 id
                 name
               }
             }
          }
        }
      }
    }
  }
}